### ISSUE TITLE
More commands

### ISSUE THREAD

**Issue by losdevpath** [JCulley/ProQuests-Documentaion#1]
I think many commands are missing in the plugin to make it a complete quest plugin.

- View player info (For users and admins, show active quests, total points, quests completed, etc)
- Add or take points to player (Possibility for admins to give or take points to a player)
- Add or take any quest to player (Possibility for admins to give or take quests to a player)

**Comment by JCulley** [comment]
Hey appreciate the suggestion, I will add a command which will return a preset list of messages replacing placeholders with those of the players specified. As for your other suggestions I encourage you to test the new beta revision as those have been included for quite some time now using the following commands:

- /quest player quest <player> start <quest identifier>
- /quest player quest <player> cancel <quest identifier>
