### ISSUE TITLE
[ERROR] Cant get past stage 2 of creating a menu

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#11]
When I try to get to the third page on creating a Quest Menu, it gives me this error:

https://pastebin.com/G1mUP73N

I'm on Spigot 1.8.8, SpigotMC account: https://www.spigotmc.org/members/joedon16.126780/

**Comment by JCulley** [comment]
You have only provided half of the error log so I am closing this issue. Feel free to reopen it with the full server log (as stated in the guidelines) so I can actually assist you.
