### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentaion#13]
The config options show the mysql database info, then right below that there's another option for username/password. What is that for? I already added my database user/pass in the options right above that.

https://i.imgur.com/V3Yrf2Q.png

**Comment by JCulley** [comment]
Please read - https://github.com/JCulley/ProQuests-Documentaion/wiki/config.yml
This also does not conform to the error guidelines - https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines

**Comment by Devillion** [comment]
my spigot account: https://www.spigotmc.org/account/
my spigot version: 1.12.2
There is no error log for this

You have 2 separate places for username and password.

Your config on the wiki only shows the username/password details in the database info. Right after that, there is another place for username/password.

I'm trying to find out why it is on there two times. Is this a mistake?

**Comment by Devillion** [comment]
I figured this out, I forgot to delete the old config/files when I added the new version. I think it was trying to combine the 2 configs, so it was messed up.
