### ISSUE TITLE
Trying to create a quest with npc

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentaion#14]
my spigot account: https://www.spigotmc.org/account/
my spigot version: 1.12.2
There is no error log for this
I'm using your latest proquests v2 plugin

I created a quest and I'm trying to set the start/end NPC.\
I made an npc with citizens, however when I try to right click the npc like the quest creator tells me to do nothing happens.
In the old version, I know we had to setup npc's in the files first. Do we have to do that in this new version too? You don't have any info on the wiki about how to setup the npc's and it looks like you removed the old info, so I'm not sure what to do.

**Comment by JCulley** [comment]
Yes, you still have to create an NPC within ProQuests. Use the in-game editor if you don't know how to configure it manually.
