### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentaion#15]
my spigot account: https://www.spigotmc.org/account/
my spigot version: 1.12.2
I'm using your latest proquests v2 plugin

I'm having this mysql error: https://pastebin.com/XpXcemHn

**Comment by JCulley** [comment]
Does not conform to guidelines:
1) Not a valid Spigot account link
2) Did not provide a markup of the entire log file
3) You didn’t provide any relevant information regarding your error. As this is a MySQL error I would need more specific info such as the MySQL version, and other specific details pertaining to your setup.

Feel free to reopen a new issue once you follow the guidelines.
