### ISSUE TITLE
Error on join 

### ISSUE THREAD

**Issue by iAzk** [JCulley/ProQuests-Documentaion#16]
Spigot Account: https://www.spigotmc.org/members/iazk.310927/
Spigot Version: 1.12.0
Link log: https://pastebin.com/0Vfe8r4Z
Others:

This error appears when I join the server, but I do not see where it comes from.
It happens to me once in 4 is when it happens the plugin disables it.

Thank you for your help

**Comment by JCulley** [comment]
1) You are not using the latest version and will not recieve support until you upgrade
2) You must provide your ENTIRE log file as stated in the guidelines.
