### ISSUE TITLE
[ISSUE] Setting up 'OBTAIN' Quest is impossible

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#18]
Spigot Profile: https://www.spigotmc.org/members/joedon16.126780/
Spigot Version: 1.8.8
Error: *no error in Console or anything from ProQuests*

When setting up an OBTAIN quest, when going to set up the required items, it asks you to right click the item. When you right click, nothing happens. I've tried doing it in inventory, out of inventory, middle click left click etc. I've also tried manually setting it up but I don't know what it's looking for to recognize it as the OBTAIN type.

All I need is a file to reference for the OBTAIN type, I don't care if there's an update or anything (I rarely use the in-game editor).

Thanks!

**Comment by JCulley** [comment]
This doesn’t make much sense to be completely honest. If you don’t know what you’re doing the creator is there to help you, I personally don’t have time to explain to everyone one on one how to configure the plugin. When it prompts you to right-click you have to be looking at a block, that’s simply how the Spigot API interprets the event.

**Comment by JoeDon16** [comment]
Right clicking a block does nothing, no error in the console either. I'm using the editor in-game trying to just create the file for an OBTAIN quest, but I can't get past this step because the right clicking does nothing.
