### ISSUE TITLE
[ISSUE] OBTAIN Quests are Impossible to Setup In-Game

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#19]
_This issue was previously closed without being answered fully. It is not possible to create an OBTAIN quest on my server because the step where you right-click a block you have to obtain **does nothing**_

Spigot Profile: https://www.spigotmc.org/members/joedon16.126780/
Spigot Version: 1.8.8
Error: no error in Console or anything from ProQuests

When setting up an OBTAIN quest, when going to set up the required items, it asks you to right click the item. When you right click, nothing happens. I've tried doing it in inventory, out of inventory, middle click left click etc. I've also tried manually setting it up but I don't know what it's looking for to recognize it as the OBTAIN type.

All I need is a file to reference for the OBTAIN type, I don't care if there's an update or anything (I rarely use the in-game editor).

Thanks!

***After this you replied telling me to right click blocks instead, which I had already tried before (you then closed the issue)***

Right clicking a block does nothing, no error in the console either. I'm using the editor in-game trying to just create the file for an obtain quest, but I can't get past this step because the right clicking does nothing.

I was just asking for a file for the obtain quest so that I could edit it from there instead of trying to guess what the file looks like due to the in-game editor being unable to complete the setup.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-25-off-v2-sale-give-players-objectives.18249/update?update=199434

**Comment by JoeDon16** [comment]
Thank you for releasing the update so quick!
