### ISSUE TITLE
Add journals

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentaion#20]
I don't see how to add a label, sorry.

I would like to see a journal that gets updated when a quest is started, in progress, completed, etc.

**Comment by JCulley** [comment]
There is an image which explains how to add a label. If anything this would be produced as an add-on as it would be rather extensive and only certain buyers would utilize such a feature.

**Comment by Devillion** [comment]
Journals are used on every other plugin as a standard featured, but an addon would be ok I guess.
