### ISSUE TITLE
[Minor] Quest Progress Bar Doesn't Work for OBTAIN Quest

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#21]
Spigot Profile: https://www.spigotmc.org/members/joedon16.126780/
Spigot Version: 1.8.8
Error: no error in Console or anything from ProQuests

When hovering over an item set to an obtain quest, it shows 'N/A' instead of the bar:
[![Screenshot from Gyazo](https://gyazo.com/97f3ce956ad2321b1a1ea917c9b930f0/raw)](https://gyazo.com/97f3ce956ad2321b1a1ea917c9b930f0)

The bar works great with the other quests though!

**Comment by JCulley** [comment]
A progress bar cannot be generated for any quest which is not numeric based.
