### ISSUE TITLE
BARRIER error - 1.7 version

### ISSUE THREAD

**Issue by Idkzito** [JCulley/ProQuests-Documentaion#22]
Account link: https://www.spigotmc.org/members/xdbrasil.307250/
Plugin version: 2.0.3.1
Spigot version: 1.7.10
Error log: https://ghostbin.com/paste/v892h

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-25-off-v2-sale-give-players-objectives.18249/update?update=199601
