### ISSUE TITLE
ProgressActions will not be fired and some suggestions

### ISSUE THREAD

**Issue by jiongjionger** [JCulley/ProQuests-Documentaion#23]
Account link: https://www.spigotmc.org/members/jiongjionger.30319/
Plugin version: 2.0.3.1
Spigot version: 1.12.2

1. ProgressActions will not be fired

2. About QuestProgressEvent
There are some problems in the design of QuestProgressEvent, for example, in the quest of BLOCKBREAK, destroying any block will call this event. That is to say, the condition of the quest does not match, and it will still fire the event.
If QuestProgressEvent is designed so, can you add a QuestProgressDoneEvent?

3. MySQL performance for huge server
You can use database connection pool to improve performance. If you use hikaricp, you only need to modify MySQLConnection's construction method and getConnection method.

Best regards

**Comment by JCulley** [comment]
1) Doesn’t make any sense
2) There is already is already a QuestCompleteEvent and a QuestCancelEvent
3) You are breaking the TOS by decompiling my work
4) This is not a suggestion or and error so I don’t know why you opened up this issue.

**Comment by jiongjionger** [comment]
1. ProgressActions will not be fired

```
start_actions:
- '[Title] a;b'
complete_actions:
- '[Title] a;b'
progress_actions:
- '[Title] a;b'
```
progress_actions does not work.

2. About QuestProgressEvent. For example, I created a quest that required the player to destroy 10 stones to complete the quest. I hope QuestProgressEvent fires only when a player breaks a stone. If QuestProgressEvent ignores task requirements (eg, break any block will fire the event), you can add a new QuestProgressDoneEvent (which fires only when the task conditions are met).
