### ISSUE TITLE
NoSuchMethodError Error - 1.7

### ISSUE THREAD

**Issue by Idkzito** [JCulley/ProQuests-Documentaion#24]
Account link: https://www.spigotmc.org/members/xdbrasil.307250/
Plugin version: 2.0.3.2
Spigot version: 1.7.10
Error log: https://ghostbin.com/paste/ss6er

**Comment by JCulley** [comment]
The link to the error log does not work

**Comment by Idkzito** [comment]
Here's: https://ghostbin.com/paste/v9sk4

**Comment by JCulley** [comment]
The Spigot version you are using is the issue as it doesn't support the hasPermission function on Entity objects.
