### ISSUE TITLE
About QuestProgressEvent and progress_actions

### ISSUE THREAD

**Issue by jiongjionger** [JCulley/ProQuests-Documentaion#25]
Account link: https://www.spigotmc.org/members/jiongjionger.30319/
Plugin version: 2.0.3.1
Spigot version: 1.12.2

I think I need to reopen this issues to provide more information. If it is disturbing you, i'm so sorry for that.

1. Quest action progress_actions does not work.

```
start_actions:
- '[Title] a;b'
complete_actions:
- '[Title] a;b'
progress_actions:
- '[Title] a;b'
```

The title is displayed normally when the quest is completed and the quest is started, but the title is not displayed during the quest. This is a bug or my wrong use?

2. QuestProgressEvent has a problem with the trigger

When I found a problem with progress_actions, I used the API to make up for it.

```
	@EventHandler
	public void onQuestProgress(QuestProgressEvent e) {
		if (e.isCancelled()) {
			return;
		}
		Quest quest = e.getQuest();
		if (quest == null) {
			return;
		}
		String questName = quest.getString(StringAttribute.IDENTIFIER);
		if (questName == null || questName.isEmpty()) {
			return;
		}
		final Player p = e.getPlayer();
		if (this.proQuestsAPI == null) {
			this.proQuestsAPI = new ProQuestsAPI();
		}
		String total = proQuestsAPI.getQuestTotal(p, questName);
		if (total == null || total.isEmpty() || total.equals("N/A")) {
			return;
		}
		String progress = proQuestsAPI.getQuestProgress(p, questName);
		if (progress == null || progress.isEmpty() || progress.equals("N/A")) {
			return;
		}
		StringBuilder mainTitle = new StringBuilder();
		mainTitle.append("§a").append(questName);

		StringBuilder subTitle = new StringBuilder();
		subTitle.append("§7进度: §6").append(progress).append(" §7/§6 ").append(total);

		Title title = new Title(mainTitle.toString(), subTitle.toString(), 5, 40, 5);

		p.sendTitle(title);
		p.playSound(p.getLocation(), Sound.ENTITY_EXPERIENCE_ORB_PICKUP, 1.0F, 1.0F);
	}
```

I created a blockbreak quest, requiring the player to destroy 128 stones, but I found that when a player breaks any block will call QuestProgressEvent. Should not QuestProgressEvent be fired only if the player breaks the stone? (Fired only when quest conditions are match).

Of course I know the existence of QuestCompletionEvent, but I would like to be prompted during the player's quest, should not use QuestProgressEvent?

English is not my native tongue, maybe my previous issues made you misunderstood, and I'm very sorry about that.

**Comment by JCulley** [comment]
The progress actions are only run when’s eh player executes the /quest progress <identified> command as can be seen on the commands and permissions page. Regardless your use of the API is wrong anyways as you shouldn’t be instantiating any new objects of the API class as it is already referenced in the main plugin instance and the API object can be retrieved via the function in there.

**Comment by jiongjionger** [comment]
It's not helpful to use ProQuests.getInstance().getAPI() instead of new ProQuestsAPI().

> I created a blockbreak quest, requiring the player to destroy 128 stones, but I found that when a player breaks any block will call QuestProgressEvent. Should not QuestProgressEvent be fired only if the player breaks the stone? (Fired only when quest conditions are match).

@JCulley

**Comment by JCulley** [comment]
You shouldn't allocate memory for an object which already exists, regardless the QuestProgressEvent runs the non quest specific checks before being run (all generalized checks). These include the timer, allowed worlds, the item in hand, regions etc. This event was specifically designed this way and should not be used as an accurate way to track quest progress. You should have been able to see this for yourself seems how you have already violated the TOS by decompiling the resource.

**Comment by jiongjionger** [comment]
But there is no event here to track the progress unless I listen to almost any bukkitevent it;s may trigger and make complex judgments. Maybe I missed something?
