### ISSUE TITLE
Spam Message/Launch quests alone

### ISSUE THREAD

**Issue by iAzk** [JCulley/ProQuests-Documentaion#27]
Spigot Account: https://www.spigotmc.org/members/iazk.310927/
Spigot Version: 1.12.0
Link log: no error in log
Others:  screen (http://prntscr.com/hi41h1)

When I log in, ProQuest sends me messages to tell me to "try another quests" and why all my quests go by themselves when I log in. Only OP have this problem

**Comment by JCulley** [comment]
Issue can easily be solved by reading the permissions tab.
