### ISSUE TITLE
Autosell Quest Not Completing

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#31]
Spigot Profile: https://www.spigotmc.org/members/joedon16.126780/
Spigot Version: 1.8.8
Error: no error in Console or anything from ProQuests

I have an Autosell quest that is set to a certain amount of money required to sell ($37440000). This works, but when I add a required item (nether_stalk), it won't complete. I have checked for hours making sure that I set it up right and I'm 99.999% sure it is. I'm checking if they've sold 1152 nether_stalk (I've tried selling way more than this, but still doesn't work), which totals the amount in the config. I also have the complete permission.

Config:
https://hastebin.com/uzeqeyikel.bash

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-25-off-v2-sale-give-players-objectives.18249/update?update=201119
