### ISSUE TITLE
[SUGGESTION] Required Crates for Crate Key Quests?

### ISSUE THREAD

**Issue by JoeDon16** [JCulley/ProQuests-Documentaion#32]
Edit: I cant add a label to this? Couldn't click the gear when opening so figured it would work after. Added the [SUGGESTION] prefix because no perms for Labels

In the plugin there is the Crate Key Quest, which works, but there is no option to add required Crates (for example: open 10 rare keys or something). I think it'd be nice to add a required crates option just like in some of the other quests.

**Comment by JCulley** [comment]
Read the guidelines.

**Comment by JoeDon16** [comment]
I don't have permission to add labels, and the quest is already in the plugin, why should I have to give you the link if you already have it in the plugin. This is a suggestion for a new option not a new quest.
