### ISSUE TITLE
Error in my console

### ISSUE THREAD

**Issue by Lunatik934** [JCulley/ProQuests-Documentaion#36]
Error : https://gist.github.com/Lunatik934/cc4a5df529ee9dbe119c7bfccc5523b9

**Spigot account: https://www.spigotmc.org/members/donston750.77155/
I use the last version of ProQuests
Server version : This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
log: https://gist.github.com/Lunatik934/d6e03b52b4ce43c9826bab9663b9f6b5**

**Comment by JCulley** [comment]
You have a configuration error with one of your delivery quests.

**Comment by Lunatik934** [comment]
https://pastebin.com/9VtfbL9M 
where is the error ?

**Comment by Lunatik934** [comment]
And when I create and menu, I have this error : https://pastebin.com/3bYtdEZq

**Comment by Lunatik934** [comment]
And https://pastebin.com/VPFnvdz1 when I start the interact quest :x this plugin are fully bugged pls fix all the bugs ...

**Comment by Lunatik934** [comment]
CAN you quickly fix all this bug pls

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-12-2-25-off-v2-sale-give-players-objectives.18249/update?update=201119
