### ISSUE TITLE
Break wheat?? :)

### ISSUE THREAD

**Issue by sebberj** [JCulley/ProQuests-Documentaion#37]
Hello my name is Sebastian and I've bought your plugin a while ago, but I've started playing minecraft and launching a new server again :)

This server contains a lot of quests, but I have encountered a small problem that I do not know how to solve :)

I'm doing a quest to harvest 50 wheat - I've tried "Break", then No. 1 when choosing a category, but I can not make it work :))
I hope you can help :)

Just say I do not know if that's the right place to ask about it :)

I'm underscoring my English :)) #Googletranslate

**Comment by JCulley** [comment]
Does not follow the guidelines https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines
