### ISSUE TITLE
[Suggestion] clans quests support

### ISSUE THREAD

**Issue by maxlehot1234** [JCulley/ProQuests-Documentaion#38]
Hi, I just want to know if you can add support for these plugins (same dev) inside ProQuests so every players from the same clan can start quests.

https://www.spigotmc.org/resources/clans-for-party-and-friends-extended-for-bungeecord.13890/
https://www.spigotmc.org/resources/party-and-friends-extended-edition-for-bungeecord-supports-1-7-1-12-2.10123/

I think it can be the same as gangs+, factions, askyblock, uskyblock, etc.

It can be considerated like a "team" quests "add-on"

Thank you so much, since I plan to buy the plugins party and friends extended edition and want to know if you can support them before buying them :P 

Have a nice day/night and hope this suggestion will not be removed from your github :(

**Comment by JCulley** [comment]
Waiting for a response from the developer of the plugin as he needs to provide me access to the resource to be able to add the feature

**Comment by JCulley** [comment]
Author responded to me stating he has no API for native Spigot plugins unless the user is utilizing Redis. Until he adds support this unfortunately will not be added.
