### ISSUE TITLE
Issue with Battlelevels killstreak

### ISSUE THREAD

**Issue by OMarseille13** [JCulley/ProQuests-Documentaion#39]
Hello,
I noticed a problem while creating a killstreak quest with battlelevels.
The 3rd page is empty so I can not choose the amount of the streak.

Could you fix this problem please ?

OMarseille13

**Comment by JCulley** [comment]
Doesn’t follow the guidelines

**Comment by OMarseille13** [comment]
Where is the answer of my question in the guidelines ? because I didn't find it

**Comment by OMarseille13** [comment]
Support is very bad. I will put a 1 star rating if I do not have any answer

**Comment by OMarseille13** [comment]
Support is very bad. I will put a 1 star rating if I do not have any response

**Comment by JCulley** [comment]
Read the guidelines and follow them if you want any support, if you can’t do so then you will not receive any it’s rather simple. https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines
