### ISSUE TITLE
Issue with Battlelevels killstreak

### ISSUE THREAD

**Issue by OMarseille13** [JCulley/ProQuests-Documentaion#40]
Hello,
I noticed a problem while creating a killstreak quest with battlelevels.
The 3rd page is empty so I can not choose the amount of the streak.

Link to spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/
Plugin version : 2.0.3.2
Spigot version : 1.8.8
Link to log : I read the log and I don't find any issue

**Comment by JCulley** [comment]
You must provide your log file.

**Comment by OMarseille13** [comment]
But there is nothing in the log because I can't finish the creation of the quest.
Check this screen : http://prntscr.com/hlpaf7

**Comment by JCulley** [comment]
If you could provide me your log as requested that would be great.

**Comment by Devillion** [comment]
he wants you whole startup log, not just proquests error

**Comment by OMarseille13** [comment]
https://pastebin.com/trhip6JU

**Comment by JCulley** [comment]
The full error log. Not just the loadup for ProQuests

**Comment by OMarseille13** [comment]
This is all the proquest log that I have today.

**Comment by JCulley** [comment]
Well from what you have provided you're SQLite never initializes so i'm going to close this issue as you still continue to not provide the information I am providing.

**Comment by OMarseille13** [comment]
But I do not have other log of proquests

**Comment by OMarseille13** [comment]
I just find that
https://pastebin.com/aBCYqiU3
