### ISSUE TITLE
issue with delivery/obtain quests

### ISSUE THREAD

**Issue by Devillion** [JCulley/ProQuests-Documentaion#41]
My spigot account: https://www.spigotmc.org/members/goflish.21294/
Just updated a few minutes ago with the latest 1.12.2 spigot version
pastebin file: there are no errors when I right click with the item: https://pastebin.com/WZKTmRQg

When I right click the required item to set the item need for obtain and delivery quests nothing happens.

https://i.imgur.com/gPWLBiX.png

**Comment by JCulley** [comment]
It seems to work fine, I would need more information to address this.

**Comment by Devillion** [comment]
I did a little more testing.

If I right click the item against another block then it works.

I deleted all my plugins with the exception of a few for testing: https://i.imgur.com/TInIBEz.png

Just thought I'd share my results. Not sure if you can do anything about it.
