### ISSUE TITLE
issues with mysql

### ISSUE THREAD

**Issue by jiongjionger** [JCulley/ProQuests-Documentaion#42]
Account link: https://www.spigotmc.org/members/jiongjionger.30319/
Plugin version: 2.0.3.1
Spigot version: 1.12.2

` [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs`

 I checked the mysql log file, I found that you use varchar to store a huge field, you can use text to replace varchar compatible with all mysql version.

**Comment by JCulley** [comment]
Does not follow the guidelines.

**Comment by jiongjionger** [comment]
interesting
