### ISSUE TITLE
What is this error

### ISSUE THREAD

**Issue by Lunatik934** [JCulley/ProQuests-Documentaion#43]
Hey, what is this error pls ?

[17:34:38 INFO]: [ProQuests] ERROR: Attempted to get duplicate itemstack for a null object

I have this error when I click in an npc with interaction quest type.

Spigot account: https://www.spigotmc.org/members/donston750.77155/
I use the last version of ProQuests
Server version : This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by JCulley** [comment]
An error check that was put in place while testing. Doesn’t affect the plugin in any way, will be removed in the next version

**Comment by Lunatik934** [comment]
It's affect my plugin, I can't click on the npc when he have an menu

but I can execute the command
