### ISSUE TITLE
Error with npc

### ISSUE THREAD

**Issue by Lunatik934** [JCulley/ProQuests-Documentaion#44]
Start NPC and End NPC module not work please fix

Spigot account: https://www.spigotmc.org/members/donston750.77155/
I use the last version of ProQuests
Server version : This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Lunatik934** [comment]
And custom command in the quest not work too :x

**Comment by JCulley** [comment]
Closed, does not include log file, also insufficient detail provided.
