### ISSUE TITLE
Question about allowed_materials

### ISSUE THREAD

**Issue by iKingM** [JCulley/ProQuests-Documentaion#45]
Link to spigot account : https://www.spigotmc.org/members/weshcanneapeche.49778/
Plugin version : 2.0.3.3
Spigot version : 1.8.8
Link to log : https://pastebin.com/We2Ei9UQ

I want to create a break quest in which player have to break blocks with a wood pickaxe but when I write "WOOD_PICKAXE;0" in allowed materials, I have this message "The value you have entered is invalid".

**Comment by PickleZPlayZ** [comment]
Same

**Comment by PickleZPlayZ** [comment]
Found a fix, use all capitals and this link: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

Make sure to use all caps and a ';' not a ':'
