### ISSUE TITLE
Data synchronization has serious problems with mysql

### ISSUE THREAD

**Issue by jiongjionger** [JCulley/ProQuests-Documentaion#48]
Account link: https://www.spigotmc.org/members/jiongjionger.30319/
Plugin version: 2.0.3.3
Spigot version: 1.12.2

When multiple servers use this plugin, data synchronization has serious problems with mysql.

For example, I finished half Q quest on server A, and then go to service B. The quest progress was reset. 

And sometimes when re-login, the quest has been reset, some quest have been completed can start again.

I use the default configuration file, the problem persists. Even increase join_delay.

I have checked a lot, make sure that each server's configuration files, quest files are the same. And MYSQL work properly.

Looking forward to your reply :)

**Comment by jiongjionger** [comment]
And console does not have any error message.

**Comment by JCulley** [comment]
Regardless if you believe your log has nothing of value, it is still requires or I will go ahead and close this issue.

**Comment by jiongjionger** [comment]
So I need to provide a log file without any error? I think you can tell you directly what information you need and I can give it to you.

**Comment by daboluo666** [comment]
Same! I posted this issues very early in the SpigotMC, but the author did not care at all.

**Comment by jiongjionger** [comment]
你需要在github上开一个issues，否则他不会理你的。
@daboluo666

**Comment by JCulley** [comment]
Log still not provided, so closing.
