### ISSUE TITLE
ProQuests Bug - NPC Click

### ISSUE THREAD

**Issue by PickleZPlayZ** [JCulley/ProQuests-Documentaion#49]
Spigot Link: https://www.spigotmc.org/members/picklez.78634/
Latest Version: Yes
Spigot Version: 1.11-R0.1-Snapshot
Error Logs: https://hastebin.com/osamidumoh.md
My Issue: See Video
Is it because of an external plugin: No

Video Link: https://www.youtube.com/watch?v=nt3sxE5vmzE&feature=youtu.be

**Comment by JCulley** [comment]
The video is unavailable so this issue is basically useless

**Comment by PickleZPlayZ** [comment]
Put it as private, not unlisted. Fixed

**Comment by JCulley** [comment]
Can not understand what the issue is from the video so please describe it with text or this issue will be closed.

**Comment by PickleZPlayZ** [comment]
NPC's don't save and nor do they work. Also Quests fail to start half the time. I can show you on the server if needed.

**Comment by JCulley** [comment]
More details are provided this is rather useless in general.

**Comment by PickleZPlayZ** [comment]
I don't know how to describe it? Can I just show you it?
