### ISSUE TITLE
Issue with MYSQL error

### ISSUE THREAD

**Issue by maxlehot1234** [JCulley/ProQuests-Documentaion#5]
I have no ideas why it occured, but do you have an idea about this?

My Spigot profile: https://www.spigotmc.org/members/maxlehot1234.6658/
I can't use Proquests betas versions :( So why this requirements was a requirement?
My  server version:
![image](https://user-images.githubusercontent.com/5159244/31855629-d6c05ce0-b67c-11e7-808d-784b28c57141.png)
The error I have in the console: https://hastebin.com/asemocopis.vbs

Thank you

**Comment by maxlehot1234** [comment]
So i am for ce to use the beta versions? This is bad. Where I can report projackpots issues/suggestions?

Also, why you not create a discord server so other people can help us?
A premium channel will be reserved for people that buy your plugins.
We can simply send you a PM on discord so you can confirm who we are.

Also closing all issues like this will not help you to fix them :P Just saying.

**Comment by maxlehot1234** [comment]
And for the issue guideline I add everything in it...

I link the spigot account
I post my spigot (paperspigot) version. You told: "  (If you're using Spigot alternatives such as PaperSpigot, Sponge etc. you may not receive support depending on the error.) ". So depends of the error, I can receive support.
I can't use Beta version since you told that you provide no support for it :P SO I use: v1.5.1.6.5
I include the issue hastebin link (pastebin alternative with colors for the code)
I read my error correctly and found something related to your plugin in it.


What's bad in my error report? Just to knoe for the next time?

**Comment by losdevpath** [comment]
"The beta release is simply for public testing and should not be run on a production server. The software is provided as is with no warranty and there will be **no support** of any kind.​"

No support for v1, and not support for beta v2. So what's the use of this? xDDD

**Comment by maxlehot1234** [comment]
@losdevpath WEIRD support ... Well, I need to deal with my error, since I can't get support...

V1.X have no support and Beta has no support too. Maybe the v0.x has support, I will try to downgrade...

@JCulley

**Comment by maxlehot1234** [comment]
@JCulley I continue to have the same error. How I can report it if we have no support for V1.X and V2.X?
