### ISSUE TITLE
Auto Starting Quests

### ISSUE THREAD

**Issue by PickleZPlayZ** [JCulley/ProQuests-Documentaion#50]
Spigot Link: https://www.spigotmc.org/members/picklez.78634/
Latest Version: Yes
Spigot Version: 1.11-R0.1-Snapshot
Error Logs: https://hastebin.com/epaborurun.md
My Issue: Quests auto-start when I don't want them too. In my quests config, I have no quests set to auto start.
Is it because of an external plugin: No

**Comment by JCulley** [comment]
Check the other permissions. https://github.com/JCulley/ProQuests-Documentaion/wiki/Commands-And-Permissions
