### ISSUE TITLE
[Suggestion] Updating Guide from 1.5.x to 2.0-GM release

### ISSUE THREAD

**Issue by CultivateMC** [JCulley/ProQuests-Documentaion#7]
Spigot Account: https://www.spigotmc.org/members/cultivatemc.112281/
Hastebin: (There is none for this issue)
Spigot Version: PaperSpigot Build 1210

I personally think this would help a lot of people who may be updating from the v1.x versions to v2.0. Many people (including myself) didn't download beta builds of the plugin since they were not meant for production servers. 

Are there any specific steps which need to be done to update the plugin? I know there was database refactoring.. but are there any other changes we need to make? Do we need to entirely remake our quests? This type of information regarding the newly released GM version would be greatly appreciated.

(Editing to match requirements, can't seem to find how to add Suggestion Label, somewhat new to Github.)

**Comment by JCulley** [comment]
As has already been stated all documentation and support related to v2.x or any newer versions will all be posted on this Github wiki page. Also it has also been noted that there should be no assumptions that any previous configurations from v1.x will work with v2.x as the entire internal code structure and formatting has been completely changed.
